name: docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: hub.docker.com
    steps:
    - uses: actions/checkout@v3
    - name: Run build bashly
      uses: addnab/docker-run-action@v3
      with:
          image: dannyben/bashly:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            bashly generate
    - name: Build and Push the Docker image
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: make docker
