name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: hub.docker.com
    steps:
    - uses: actions/checkout@v3
    #- name: Build Bashly
    #  run: make build
    - name: Build and Push the Docker image
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: make docker
