name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: rancher/dind
    steps:
    - uses: actions/checkout@v3
    - name: Build Bashly
      run: make build
    - name: Build and Push the Docker image
      run: DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD make docker
